### PR TITLE
bump eventmachine dependency to 1.2.7, add rvm and asdf files for loc…

### PR DESCRIPTION
**Pull request by karlosmid**
…al development env. set webpack to version four.

### CODE REVIEW

**Comment by karlosmid** [comment]
Hi!

eventmachine had segmentation fault bugs that were resolved in latest version of eventmachine.

**Comment by jcoglan** [comment]
I'm not sure why this library should bump its EventMachine dependency because EM released a bug fix. What's the reason for all the other dependency config added here?

**Comment by karlosmid** [comment]
Hi! Those are rvm and asdf configuration files that help setting up a local development environment. But those must not be part of this update.

Maybe I do not know enough about bundler, but I was not able to run my rails project with the latest eventmachine gem because faye gem was locked to 1.0.0 version of event machine.

**Comment by jcoglan** [comment]
Can you show me your `Gemfile` and `Gemfile.lock` from before you upgraded any gems?

**Comment by karlosmid** [comment]
Hi, you mean for this faye reposistory or our original project where we use faye?

**Comment by jcoglan** [comment]
The one from your application that was locking eventmachine at an old version.

**Comment by karlosmid** [comment]
Gemfile

```
source 'https://rubygems.org'

gem 'eventmachine', '~> 1.0.9.1'

gem 'cancan'

gem 'rubyXL', '3.4.14'
gem 'rubyzip', '1.3.0'

gem 'pg' #, '~> 0.18.4'
#gem 'font-awesome-rails', '~> 4.6', '>= 4.6.2.0'
gem 'font-awesome-rails', '~> 4.6', '>= 4.6.3.1'


gem 'mini_magick'
gem 'write_xlsx', '~> 0.83.0'
gem 'prawn'

gem 'puma', '~> 4.3', '>= 4.3.7'
#gem 'net-ssh', '~> 2.9.2'
gem 'net-ssh', '~> 6.1.0'
gem 'connection_ninja'

gem 'google-api-client' #, '0.13.0'
#gem 'addressable', '2.5.1'
#gem 'httpclient', '2.8.3'
#gem 'googleauth', '0.5.1'
#gem 'mime-types', '3.1'
#gem 'representable', '3.0.4'
#gem 'retriable', '3.0.2'


gem 'gmail'

gem 'net-sftp'
gem 'net-telnet'

#gem 'headless', '~> 2.2', '>= 2.2.3'
#gem 'headless', '2.3.1'
gem 'watir', '~> 6.16.5'
#gem 'watir-extensions-element-screenshot'
#gem 'watir-webdriver' , '0.9.9'
#gem 'watir-webdriver-performance', '~> 0.2.4'
#gem 'selenium-webdriver', '2.53.4'
gem 'webdrivers', '~> 4.2.0'
#gem 'selenium-webdriver', '2.46.2'
#gem 'appium_lib', '7.0.0' #gem install appium_lib -v 8.0.2
gem 'appium_lib', '~> 10.5.0'

gem 'faye'
gem 'faye-rails'
gem 'faye-redis'
gem 'faye-websocket'
gem "devise_ldap_authenticatable" #, :git => "git://github.com/cschiewek/devise_ldap_authenticatable.git"
gem 'jquery-datatables-rails'
gem 'jquery-ui-rails'

gem 'codemirror-rails'

gem 'json'


#gem 'rack-mini-profiler'
# For memory profiling (requires Ruby MRI 2.1+)
#gem 'memory_profiler'

# For call-stack profiling flamegraphs (requires Ruby MRI 2.0.0+)
#gem 'flamegraph'
#gem 'stackprof'     # For Ruby MRI 2.1+

gem 'sassc-rails'
gem 'rails'#, '4.2.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
#gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '~> 3.0' #, '>= 3.0.4'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc





# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'testlink-api-client', github: "karlosmid/testlink-api-client"
group :development do
  gem 'letter_opener_web', '1.3.4'
end
gem 'rspec'
gem 'sequel'
#capistrano
group :development do
  gem 'capistrano',         require: false
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma',   require: false
  gem 'capistrano-scm-gitcopy',  require: false
end

gem 'sshkit', '~> 1.21'
gem 'net-scp', '~> 3.0.0.rc1'
gem 'sendgrid-actionmailer', '~> 2.4.0'
gem 'x25519'
gem 'ed25519', '>= 1.2', '< 2.0'
gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'
gem 'i18n'
gem "roo", "~> 2.7.1"
gem 'archive-zip'
```

**Comment by karlosmid** [comment]
Gemfile.lock

```
GIT
  remote: https://github.com/karlosmid/testlink-api-client.git
  revision: 46b0370c2059c583fc9ee0dc3dd4f6df6e92a95c
  specs:
    testlink-api-client (0.0.3)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.0.7.2)
      actionpack (= 5.0.7.2)
      nio4r (>= 1.2, < 3.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.7.2)
      actionpack (= 5.0.7.2)
      actionview (= 5.0.7.2)
      activejob (= 5.0.7.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.7.2)
      actionview (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.7.2)
      activesupport (= 5.0.7.2)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.0.7.2)
      activesupport (= 5.0.7.2)
      globalid (>= 0.3.6)
    activemodel (5.0.7.2)
      activesupport (= 5.0.7.2)
    activerecord (5.0.7.2)
      activemodel (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      arel (~> 7.0)
    activesupport (5.0.7.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    airbrussh (1.4.0)
      sshkit (>= 1.6.1, != 1.7.0)
    appium_lib (10.5.0)
      appium_lib_core (~> 3.3)
      nokogiri (~> 1.8, >= 1.8.1)
      tomlrb (~> 1.1)
    appium_lib_core (3.11.0)
      faye-websocket (~> 0.11.0)
      selenium-webdriver (~> 3.14, >= 3.14.1)
    archive-zip (0.12.0)
      io-like (~> 0.3.0)
    arel (7.1.4)
    bcrypt (3.1.15)
    bcrypt_pbkdf (1.0.1)
    bcrypt_pbkdf (1.0.1-x64-mingw32)
    builder (3.2.4)
    cancan (1.6.10)
    capistrano (3.14.1)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (2.0.1)
      capistrano (~> 3.1)
    capistrano-rails (1.6.1)
      capistrano (~> 3.1)
      capistrano-bundler (>= 1.1, < 3)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    capistrano-scm-gitcopy (0.1.5)
      capistrano (~> 3.0)
    capistrano3-puma (4.0.0)
      capistrano (~> 3.7)
      capistrano-bundler
      puma (~> 4.0)
    childprocess (3.0.0)
    codemirror-rails (5.16.0)
      railties (>= 3.0, < 6.0)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.7)
    connection_ninja (0.4.1)
    cookiejar (0.3.3)
    crass (1.0.6)
    declarative (0.0.20)
    declarative-option (0.1.0)
    devise (4.7.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise_ldap_authenticatable (0.8.7)
      devise (>= 3.4.1)
      net-ldap (>= 0.16.0)
    diff-lcs (1.4.4)
    ed25519 (1.2.4)
    em-hiredis (0.3.1)
      eventmachine (~> 1.0)
      hiredis (~> 0.6.0)
    em-http-request (1.1.7)
      addressable (>= 2.3.4)
      cookiejar (!= 0.3.1)
      em-socksify (>= 0.3)
      eventmachine (>= 1.0.3)
      http_parser.rb (>= 0.6.0)
    em-socksify (0.3.2)
      eventmachine (>= 1.0.0.beta.4)
    erubis (2.7.0)
    eventmachine (1.0.9.1)
    execjs (2.7.0)
    faraday (0.17.3)
      multipart-post (>= 1.2, < 3)
    faye (1.1.2)
      cookiejar (>= 0.3.0)
      em-http-request (>= 0.3.0)
      eventmachine (>= 0.12.0)
      faye-websocket (>= 0.9.1)
      multi_json (>= 1.0.0)
      rack (>= 1.0.0)
      websocket-driver (>= 0.5.1)
    faye-rails (2.0.3)
      eventmachine (~> 1.0.0)
      faye (= 1.1.2)
    faye-redis (0.2.0)
      em-hiredis (>= 0.2.0)
      eventmachine (>= 0.12.0)
      multi_json (>= 1.0.0)
    faye-websocket (0.11.0)
      eventmachine (>= 0.12.0)
      websocket-driver (>= 0.5.1)
    ffi (1.13.1)
    ffi (1.13.1-x64-mingw32)
    font-awesome-rails (4.7.0.5)
      railties (>= 3.2, < 6.1)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    gmail (0.7.1)
      gmail_xoauth (>= 0.3.0)
      mail (>= 2.2.1)
    gmail_xoauth (0.4.2)
      oauth (>= 0.3.6)
    google-api-client (0.32.1)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.5, < 0.10.0)
      httpclient (>= 2.8.1, < 3.0)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
      signet (~> 0.10)
    googleauth (0.9.0)
      faraday (~> 0.12)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (~> 0.7)
    hiredis (0.6.3)
    http_parser.rb (0.6.0)
    httpclient (2.8.3)
    i18n (1.8.5)
      concurrent-ruby (~> 1.0)
    io-like (0.3.1)
    jbuilder (2.10.0)
      activesupport (>= 5.0.0)
    jquery-datatables-rails (3.4.0)
      actionpack (>= 3.1)
      jquery-rails
      railties (>= 3.1)
      sass-rails
    jquery-rails (4.4.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    json (1.8.6)
    jwt (2.2.2)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.7.0)
      launchy (~> 2.2)
    letter_opener_web (1.3.4)
      actionmailer (>= 3.2)
      letter_opener (~> 1.0)
      railties (>= 3.2)
    libv8 (3.16.14.19)
    loofah (2.7.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    memoist (0.16.2)
    method_source (1.0.0)
    mini_magick (4.10.1)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.14.2)
    multi_json (1.15.0)
    multipart-post (2.1.1)
    net-ldap (0.16.3)
    net-scp (3.0.0)
      net-ssh (>= 2.6.5, < 7.0.0)
    net-sftp (3.0.0)
      net-ssh (>= 5.0.0, < 7.0.0)
    net-ssh (6.1.0)
    net-telnet (0.2.0)
    nio4r (2.5.2)
    nokogiri (1.10.10)
      mini_portile2 (~> 2.4.0)
    nokogiri (1.10.10-x64-mingw32)
      mini_portile2 (~> 2.4.0)
    oauth (0.5.4)
    orm_adapter (0.5.0)
    os (1.1.1)
    pdf-core (0.7.0)
    pg (1.2.3)
    pg (1.2.3-x64-mingw32)
    prawn (2.2.2)
      pdf-core (~> 0.7.0)
      ttfunk (~> 1.5)
    public_suffix (4.0.5)
    puma (4.3.7)
      nio4r (~> 2.0)
    rack (2.2.3)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.7.2)
      actioncable (= 5.0.7.2)
      actionmailer (= 5.0.7.2)
      actionpack (= 5.0.7.2)
      actionview (= 5.0.7.2)
      activejob (= 5.0.7.2)
      activemodel (= 5.0.7.2)
      activerecord (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      bundler (>= 1.3.0)
      railties (= 5.0.7.2)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (5.0.7.2)
      actionpack (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (13.0.1)
    rdoc (4.3.0)
    ref (2.0.0)
    regexp_parser (1.7.1)
    representable (3.0.4)
      declarative (< 0.1.0)
      declarative-option (< 0.2.0)
      uber (< 0.2.0)
    responders (2.4.1)
      actionpack (>= 4.2.0, < 6.0)
      railties (>= 4.2.0, < 6.0)
    retriable (3.1.2)
    roo (2.7.1)
      nokogiri (~> 1)
      rubyzip (~> 1.1, < 2.0.0)
    rspec (3.9.0)
      rspec-core (~> 3.9.0)
      rspec-expectations (~> 3.9.0)
      rspec-mocks (~> 3.9.0)
    rspec-core (3.9.2)
      rspec-support (~> 3.9.3)
    rspec-expectations (3.9.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-mocks (3.9.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-support (3.9.3)
    rubyXL (3.4.14)
      nokogiri (>= 1.10.8)
      rubyzip (>= 1.3.0)
    ruby_http_client (3.5.1)
    rubyzip (1.3.0)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc (2.4.0-x64-mingw32)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    sdoc (0.4.2)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    selenium-webdriver (3.142.7)
      childprocess (>= 0.5, < 4.0)
      rubyzip (>= 1.2.2)
    sendgrid-actionmailer (2.4.2)
      mail (~> 2.5)
      sendgrid-ruby (~> 6.0)
    sendgrid-ruby (6.3.4)
      ruby_http_client (~> 3.4)
    sequel (5.35.0)
    signet (0.11.0)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.2)
    sshkit (1.21.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
    thor (1.0.1)
    thread_safe (0.3.6)
    tilt (2.0.10)
    tomlrb (1.3.0)
    ttfunk (1.5.1)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.7)
      thread_safe (~> 0.1)
    tzinfo-data (1.2020.1)
      tzinfo (>= 1.0.0)
    uber (0.1.0)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)
    warden (1.2.9)
      rack (>= 2.0.9)
    watir (6.16.5)
      regexp_parser (~> 1.2)
      selenium-webdriver (~> 3.6)
    webdrivers (4.2.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (>= 3.0, < 4.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    write_xlsx (0.83.0)
      rubyzip (>= 1.0.0)
      zip-zip
    x25519 (1.0.8)
    zip-zip (0.3)
      rubyzip (>= 1.0.0)

PLATFORMS
  ruby
  x64-mingw32

DEPENDENCIES
  appium_lib (~> 10.5.0)
  archive-zip
  bcrypt_pbkdf (>= 1.0, < 2.0)
  cancan
  capistrano
  capistrano-bundler
  capistrano-rails
  capistrano-rvm
  capistrano-scm-gitcopy
  capistrano3-puma
  codemirror-rails
  coffee-rails (~> 4.1.0)
  connection_ninja
  devise_ldap_authenticatable
  ed25519 (>= 1.2, < 2.0)
  eventmachine (~> 1.0.9.1)
  faye
  faye-rails
  faye-redis
  faye-websocket
  font-awesome-rails (~> 4.6, >= 4.6.3.1)
  gmail
  google-api-client
  i18n
  jbuilder (~> 2.0)
  jquery-datatables-rails
  jquery-rails
  jquery-ui-rails
  json
  letter_opener_web (= 1.3.4)
  mini_magick
  net-scp (~> 3.0.0.rc1)
  net-sftp
  net-ssh (~> 6.1.0)
  net-telnet
  pg
  prawn
  puma (~> 4.3, >= 4.3.7)
  rails
  roo (~> 2.7.1)
  rspec
  rubyXL (= 3.4.14)
  rubyzip (= 1.3.0)
  sassc-rails
  sdoc (~> 0.4.0)
  sendgrid-actionmailer (~> 2.4.0)
  sequel
  sqlite3
  sshkit (~> 1.21)
  testlink-api-client!
  therubyracer
  turbolinks
  tzinfo-data
  uglifier (~> 3.0)
  watir (~> 6.16.5)
  webdrivers (~> 4.2.0)
  write_xlsx (~> 0.83.0)
  x25519

BUNDLED WITH
   2.1.4
```

**Comment by jcoglan** [comment]
The things that are actually stopping you from being able to upgrade `eventmachine` are the gems `em-hiredis` and `faye-rails`, which both have a dependency of `eventmachine ~> 1.0`. We're not able to do anything about those dependencies.

**Comment by jcoglan** [comment]
Making `faye` depend on `eventmachine >= 1.2` would actually make it impossible for your app to build because this would conflict with other gems that require `eventmachine ~> 1.0`.

**Comment by karlosmid** [comment]
Got it. I managed to build with the latest eventmachine by forking all relevant libraries.

**Pull request closed without merging**
