### PR TITLE
Define proper constructor for class

### PR DESCRIPTION
**Pull request by cravler**

### CODE REVIEW

**Comment by jcoglan** [comment]
Hi @cravler can you explain why you're adding this functionality? What problem does it solve and how are you planning on using it?

**Comment by cravler** [comment]
I need access to "WebSocket._unloaded" property.

```js
client.disable('autodisconnect');
if (browser.Event && global.onbeforeunload !== undefined) {
    browser.Event.on(global, 'beforeunload', function() {
        if (client._dispatcher._transport.constructor._unloaded) {
            client._dispatcher._transport.constructor._unloaded = false;
        }
    });
}
```

**Comment by jcoglan** [comment]
Can we step back -- what's the ultimate problem you're trying to solve? What led you to trying to set the `_unloaded` property here?

**Comment by cravler** [comment]
If 'window.location=download_url' is used then websocket disconnected and stop working

**Comment by jcoglan** [comment]
Apologies for the delay on this, I've not been well the last month or so.

Rather than trying to get access to internal implementation details, we could just make it so that `disable('autodisconnect')` stopped the `_unloaded` flag being set in the WebSocket module. Would you like to have a go at implementing that?

**Comment by jcoglan** [comment]
@cravler Just checking whether you saw my last comment -- would you be able to amend your PR to implement my suggestion?

**Comment by jcoglan** [comment]
@cravler I've implemented the fix as I suggested and I'm going to close this PR. Hopefully this achieves the functionality you want without having to dig into the internals.

**Pull request closed without merging**
