### PR TITLE
workaround for IE 8 XDomainRequest garbage collection issue

### LINKED ISSUE #382: IE 8 XDomainRequest fails randomly
It seems that XDR sometimes gets garbage collected if there are no references to the object.

Explanation and workaround suggested here:
http://stackoverflow.com/questions/8058446/ie-xdomainrequest-not-always-work/27583212#27583212

The bug only affects IE 8, since XDR isn't in IE 7, and the GC issue seems to be gone in IE 9. I've only been able to reproduce it in IE 11's version 8 compatibility mode. I was unable to confirm using a VM running a real IE 8. Reproducibility also seems to be affected by the complexity of the page that Faye lives on (probably because other elements/scripts could affect GC timing).

The suggested fix in the stackoverflow post seems to work, in that if I add something similar to Faye's code them I'm unable to reproduce the issue anymore in IE 8 compatibility mode.

### PR DESCRIPTION
**Pull request by jkarneges**
fixes #382

### CODE REVIEW

**Comment by jcoglan** [comment]
I'm wondering if this could be improved by using https://github.com/faye/faye/blob/master/javascript/util/set.js to store the request objects -- using `indexOf` and `splice` means removing elements is at least O(n) whereas it could be constant-time using a `Set`. What do you think?

**Comment by jcoglan** [comment]
And also, thank you for discovering this issue in the first place :)

**Comment by jkarneges** [comment]
Not sure if there will ever be enough parallel XDRs that this will affect performance, but ``Set`` is the proper data structure. :)

**Comment by jcoglan** [comment]
There are still a couple of issues with this code. `var pendingXHR` creates a new top-level variable, which we try to avoid doing. Better to make this array a property of the `Faye.Transport.CORS` class.

Second, this code won't work as-is: `Faye.Set` requires values to have a unique `id` property to be indexed. This code as written will probably only allow one request to exist, since it will use the stringified value of the request object has the key.

Could you fix these issues and then squash the commits?

**Comment by jkarneges** [comment]
How do you suggest generating a unique id? Do you know if it's safe to set a property on XDomainRequest? We could try to set xdr.id, but I wonder if that's risky. Assuming we can set properties at all, my thought is to set a private property (e.g. xdr._fayeId), add a wrapper object to the Faye.Set (e.g. {id: xdr._fayeId, xdr: xdr}), and then remake the wrapper object at lookup time.

**Comment by jcoglan** [comment]
I've merged this and made some fixes. Sorry I didn't respond earlier but I'm now trying to get a release done and I don't have much time.

**Comment by jkarneges** [comment]
No complaints here. Your way looks better.

**Pull request merged**
