### PR TITLE
removed json2 library

### PR DESCRIPTION
**Pull request by thesmart**
I removed json2 library and the build and tests seems to all pass.

### CODE REVIEW

**Comment by jcoglan** [comment]
I'm not sure why you've also removed compatibility with Prototype while making this change. We can still preserve that but we need to call `JSON.stringify` instead of `Faye.stringify`. The one issue I'm concerned about is that to do this, we need to call:

```js
JSON.stringify(message, function(key, value) {
  return this instanceof Array ? this[key] : value;
});
```

I recall that some old browsers don't support the `function(key, value)` argument to this function, and so you cannot make them compatible with Prototype. In such browsers you need to load `json2.js`, but `json2.js` will not override the native `JSON` object if it already exists. So you need to modify `json2.js` to make it work in such scenarios, which is what Faye's copy does.

Trouble is I can't remember which browsers are affected by this so I don't know how much of a risk it is.

**Comment by fatso83** [comment]
SauceLabs and similar often give out free accounts to open source projects. I'd suggest @thesmart to run the test suite against an array of typical older browsers to spot which browsers will break.

**Comment by squadette** [comment]
@jcoglan will JSON3 be better for this?

"Utilizes feature tests to detect broken or incomplete native JSON implementations (JSON 2 only checks for the presence of the native functions)."

**Comment by jcoglan** [comment]
@squadette @fatso83 @thesmart On the `node-modules` branch I've been working on converting the JS codebase to use CommonJS module format; which has had the side effect of removing `json2.js`, since it's not something you can `require` -- `JSON` is assumed to be present as a global.

At this point it is probably safe for many apps to make this assumption about the browser, and they can include `json2.js` or `json3.js` to provide `JSON` as they need.

Note that the compatibility with Prototype/Mootools that this PR removes is preserved on the `node-modules` branch and so it requires that `JSON.stringify()` implements the callback argument shown in the examples above.

Does `json3.js` make sure that such a `JSON.stringify()` function exists?

**Comment by squadette** [comment]
@jcoglan it looks like this to me: https://github.com/bestiejs/json3#javascript-engines and https://github.com/bestiejs/json3/blob/master/lib/json3.js#L899

(I'm not really a modern JavaScript developer, though).

**Comment by jcoglan** [comment]
I'm going to close this because it's been done on the `node-modules` branch, and in a way that doesn't break Prototype compat.

The choice of which JSON implementation to use should now be entirely up to the user.

**Pull request closed without merging**
